### ISSUE TITLE
Make this work in "Pointer only" mode 

### ISSUE THREAD

**Issue by Hellisotherpeople** [IBM/MAX-Text-Summarizer#20]
Lets say that I want a strictly extractive summarizer - e.g. I want something analogous to a highlighter and will not mix up word order from an original text. 

Can MAX work like this?

**Comment by MLnick** [comment]
cc @I-Hong @xuhdev

**Comment by autoih** [comment]
Thanks @Hellisotherpeople for your interests in MAX model. If you would prefer to have a summarized result, which every word comes from the source document. In this case, the model may not generate a result in that way, since one of the advantages of the model is to provide a summarized result including `novel` words(doesn't exist in the source document), mentioned in the [paper](https://arxiv.org/abs/1704.04368).
